### ISSUE TITLE
Name already used

### ISSUE THREAD

**Issue by megatux** [mlajtos/mosaic#24]
Did you know the venerable NCSA Mosaic? The second browser in history! I still remember trying it. 
I think it's not a good idea to steal that name.

Some sites still available:

* https://snapcraft.io/mosaic
* https://github.com/alandipert/ncsa-mosaic

**Comment by mlajtos** [comment]
https://github.com/mlajtos/mosaic/blob/master/DesignDecisions.md#mosaic

It was a conscious decision to pay homage. Nobody really uses it anymore and it was officially been dead (no development, no support) for almost 24 years. I think it is safe until some lawyer will put their soul into this. :)

**Comment by niutech** [comment]
I still think it is an unfortunate decision to name your project Mosaic. The original Mosaic browser not being used does not mean it is not being searched for. In fact, NCSA Mosaic was the first popular web browser, so it is still recognizable for historical reasons. There are 78,800,000 results in Google for `Mosaic browser`. Stealing its fame is not paying homage. Consider changing your project name.
