### ISSUE TITLE
Enable horizontal scrolling

### ISSUE THREAD

**Issue by niutech** [mlajtos/mosaic#28]
[Stack](https://getstack.app/) app has a very useful functionality - horizontal scrolling of opened web apps (see the scrollbar at the bottom):
 
![Stack](https://user-images.githubusercontent.com/384997/95118647-f5ef3100-074a-11eb-8ec5-0e0ab8602437.png)

However, it is closed source. Can Mosaic have a similar feature?

**Comment by mlajtos** [comment]
Horizontal scrolling will be same as in every other browser -- scrolling a webpage or navigating back/forward.

Again, don't be discouraged by their business model -- they are trying awesome and radical stuff and if you like that direction, please consider subscribing to their plans. I like their [master plan](https://getstack.app/blog/you-too-can-be-a-superhuman) a lot and they have done a ton of great work.
