### ISSUE TITLE
Stack app features

### ISSUE THREAD

**Issue by niutech** [mlajtos/mosaic#32]
[Stack](https://getstack.app) is an interesting new web browser, which allows you to browse web apps/pages in workspaces and columns. However, it is closed source and freemium. It would be great to have an open source alternative to it and your project is a good starting point. Would you mind adding some useful features from Stack, such as:
- stacks (switchable on the left sidebar)
- workspaces (switchable at the top left corner)
- multiple accounts
- horizontal scrolling (issue #28)
- suspending inactive tabs
- temporary ghost pages
- desktop notifications
- fullscreen support
- auto refresh

Thanks!

**Comment by mlajtos** [comment]
I tried Stack before starting this project. I felt really constrained by the fixed layout and horizontal scrolling was driving me mad -- I want to go back, not scroll (!). Being closed source and freemium is kinda good thing -- better focus on product rather community and stuff.

It seems like you enjoy using Stack, but Mosaic tries to be something different -- a basic browser that does not stand in a way and fades into background. I am sorry, but these features you listed I see as distractions. Except proper fullscreen mode which I desperately need. :)
