### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mlajtos** [mlajtos/mosaic#6]
[ ] setup Github Action for Linux packages (DEB, RPM)
[ ] get package to AUR (somehow)

**Comment by TheOPtimal** [comment]
I'd be willing to write the PKGBUILD and test it, as I run Manjaro.

**Comment by michalklempa** [comment]
Anybody has an idea why this fails: https://github.com/michalklempa/mosaic/runs/975109497?check_suite_focus=true
Have created a ticket here: https://github.com/samuelmeuli/action-electron-builder/issues/42

**Comment by mlajtos** [comment]
@TheOPtimal Hey, please checkout [v0.0.2](https://github.com/mlajtos/mosaic/releases/tag/v0.0.2). There is a package for Arch (and other Linux packages as well).
